// lib/firebase_options.dart
// ⚠️  IMPORTANT: This file is generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
// Then: flutterfire configure --project=airtaskflow
// That will replace this file with your real config.
//
// For now, here is a MANUAL template you can fill in from your
// Firebase Console → Project Settings → Your apps → Web app config:

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      default: return web;
    }
  }

  // ── REPLACE THESE VALUES from Firebase Console ─────────────────────────────
  // Console → Project Settings → Your apps → Web → SDK setup and configuration
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAgZbd8aSaCydfCcLbt0Mfi3NGimrJ_oqs",
      authDomain: "airtaskflow.firebaseapp.com",
      projectId: "airtaskflow",
      storageBucket: "airtaskflow.firebasestorage.app",
      messagingSenderId: "384015413010",
      appId: "1:384015413010:web:1771ce2533f47d40930dcb",
      measurementId: "G-MGJYJW3MCP"
  );


}
